from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import os
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from generatePDF import generate_work

pdfmetrics.registerFont(TTFont("DejaVuSans", "DejaVuSans.ttf"))

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        name_tabels = ['Кинематика', 'Динамика', 'Законы сохранения', 'Статика, гидростатика',
                       'Молекулярная физика',
                       'Термодинамика', 'Электростатика', 'Законы постоянного тока', 'Электромагнетизм',
                       'Колебания и волны', 'Оптика и СТО',
                       'Квантовая, атомная и ядерная физика']

        def ln_tables(number):
            f = open("Формулы/" + name_tabels[number-1] + ".txt", encoding="utf-8")
            count = 0
            for line in f:
                count += 1
            f.close()
            return count
        def ln_tables_o(number):
            f = open("Определения/" + name_tabels[number-1] + ".txt", encoding="utf-8")
            count = 0
            for line in f:
                count += 1
            f.close()
            return count
        def ln_tables_o_o(number):
            f = open("Определения ответы/" + name_tabels[number-1] + ".txt", encoding="utf-8")
            count = 0
            for line in f:
                count += 1
            f.close()
            return count

        Dialog.setObjectName("Dialog")
        Dialog.resize(436, 637)
        Dialog.setMouseTracking(False)
        Dialog.setTabletTracking(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, -30, 451, 671))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(210, 20, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser.setFont(font)
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(310, 20, 111, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setUnderline(False)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setMouseTracking(False)
        self.textBrowser_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser_2.setLineWidth(1)
        self.textBrowser_2.setMidLineWidth(0)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 70, 181, 31))
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 110, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_6.setGeometry(QtCore.QRect(10, 190, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_7.setGeometry(QtCore.QRect(10, 230, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_7.setFont(font)
        self.textBrowser_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_8.setGeometry(QtCore.QRect(10, 270, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_8.setFont(font)
        self.textBrowser_8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_9.setGeometry(QtCore.QRect(10, 310, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_9.setFont(font)
        self.textBrowser_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_10.setGeometry(QtCore.QRect(10, 350, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_10.setFont(font)
        self.textBrowser_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_11.setGeometry(QtCore.QRect(10, 390, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_11.setFont(font)
        self.textBrowser_11.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_12.setGeometry(QtCore.QRect(10, 430, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_12.setFont(font)
        self.textBrowser_12.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_13.setGeometry(QtCore.QRect(10, 470, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_13.setFont(font)
        self.textBrowser_13.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_14.setGeometry(QtCore.QRect(10, 510, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_14.setFont(font)
        self.textBrowser_14.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_15.setGeometry(QtCore.QRect(10, 550, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_15.setFont(font)
        self.textBrowser_15.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textBrowser_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setEnabled(True)
        self.spinBox.setGeometry(QtCore.QRect(220, 70, 71, 31))
        self.spinBox.setMaximum(ln_tables(1))
        self.spinBox.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox.setSpecialValueText("")
        self.spinBox.setAccelerated(False)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setGeometry(QtCore.QRect(330, 70, 71, 31))
        self.spinBox_2.setWrapping(True)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(11)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setAutoFillBackground(False)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_2.setMaximum(ln_tables_o(1))
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton.setGeometry(QtCore.QRect(220, 590, 185, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_3.setEnabled(True)
        self.spinBox_3.setGeometry(QtCore.QRect(220, 110, 71, 31))
        self.spinBox_3.setMaximum(ln_tables(2))
        self.spinBox_3.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_3.setSpecialValueText("")
        self.spinBox_3.setAccelerated(False)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_4.setEnabled(True)
        self.spinBox_4.setGeometry(QtCore.QRect(220, 150, 71, 31))
        self.spinBox_4.setMaximum(ln_tables(3))
        self.spinBox_4.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_4.setFont(font)
        self.spinBox_4.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_4.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_4.setSpecialValueText("")
        self.spinBox_4.setAccelerated(False)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_5.setEnabled(True)
        self.spinBox_5.setGeometry(QtCore.QRect(220, 190, 71, 31))
        self.spinBox_5.setMaximum(ln_tables(4))
        self.spinBox_5.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_5.setFont(font)
        self.spinBox_5.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_5.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_5.setSpecialValueText("")
        self.spinBox_5.setAccelerated(False)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_6.setEnabled(True)
        self.spinBox_6.setGeometry(QtCore.QRect(220, 230, 71, 31))
        self.spinBox_6.setMaximum(ln_tables(5))
        self.spinBox_6.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_6.setFont(font)
        self.spinBox_6.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_6.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_6.setSpecialValueText("")
        self.spinBox_6.setAccelerated(False)
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_7.setEnabled(True)
        self.spinBox_7.setGeometry(QtCore.QRect(220, 270, 71, 31))
        self.spinBox_7.setMaximum(ln_tables(6))
        self.spinBox_7.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_7.setFont(font)
        self.spinBox_7.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_7.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_7.setSpecialValueText("")
        self.spinBox_7.setAccelerated(False)
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_8 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_8.setEnabled(True)
        self.spinBox_8.setGeometry(QtCore.QRect(220, 310, 71, 31))
        self.spinBox_8.setMaximum(ln_tables(7))
        self.spinBox_8.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_8.setFont(font)
        self.spinBox_8.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_8.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_8.setSpecialValueText("")
        self.spinBox_8.setAccelerated(False)
        self.spinBox_8.setObjectName("spinBox_8")
        self.spinBox_9 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_9.setEnabled(True)
        self.spinBox_9.setGeometry(QtCore.QRect(220, 350, 71, 31))
        self.spinBox_9.setMaximum(ln_tables(8))
        self.spinBox_9.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_9.setFont(font)
        self.spinBox_9.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_9.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_9.setSpecialValueText("")
        self.spinBox_9.setAccelerated(False)
        self.spinBox_9.setObjectName("spinBox_9")
        self.spinBox_10 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_10.setEnabled(True)
        self.spinBox_10.setGeometry(QtCore.QRect(220, 390, 71, 31))
        self.spinBox_10.setMaximum(ln_tables(9))
        self.spinBox_10.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_10.setFont(font)
        self.spinBox_10.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_10.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_10.setSpecialValueText("")
        self.spinBox_10.setAccelerated(False)
        self.spinBox_10.setObjectName("spinBox_10")
        self.spinBox_11 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_11.setEnabled(True)
        self.spinBox_11.setGeometry(QtCore.QRect(220, 430, 71, 31))
        self.spinBox_11.setMaximum(ln_tables(10))
        self.spinBox_11.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_11.setFont(font)
        self.spinBox_11.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_11.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_11.setSpecialValueText("")
        self.spinBox_11.setAccelerated(False)
        self.spinBox_11.setObjectName("spinBox_11")
        self.spinBox_12 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_12.setEnabled(True)
        self.spinBox_12.setGeometry(QtCore.QRect(220, 470, 71, 31))
        self.spinBox_12.setMaximum(ln_tables(11))
        self.spinBox_12.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_12.setFont(font)
        self.spinBox_12.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_12.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_12.setSpecialValueText("")
        self.spinBox_12.setAccelerated(False)
        self.spinBox_12.setObjectName("spinBox_12")
        self.spinBox_13 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_13.setEnabled(True)
        self.spinBox_13.setGeometry(QtCore.QRect(220, 510, 71, 31))
        self.spinBox_13.setMaximum(ln_tables(12))
        self.spinBox_13.setWrapping(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_13.setFont(font)
        self.spinBox_13.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_13.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_13.setSpecialValueText("")
        self.spinBox_13.setAccelerated(False)
        self.spinBox_13.setObjectName("spinBox_13")
        self.spinBox_14 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_14.setEnabled(True)
        self.spinBox_14.setGeometry(QtCore.QRect(220, 550, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_14.setFont(font)
        self.spinBox_14.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_14.setWrapping(True)
        self.spinBox_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_14.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_14.setSpecialValueText("")
        self.spinBox_14.setAccelerated(False)
        self.spinBox_14.setObjectName("spinBox_14")
        self.spinBox_15 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_15.setEnabled(True)
        self.spinBox_15.setGeometry(QtCore.QRect(330, 110, 71, 31))
        self.spinBox_15.setMaximum(ln_tables_o(2))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_15.setFont(font)
        self.spinBox_15.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_15.setWrapping(True)
        self.spinBox_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_15.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_15.setSpecialValueText("")
        self.spinBox_15.setAccelerated(False)
        self.spinBox_15.setObjectName("spinBox_15")
        self.spinBox_16 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_16.setEnabled(True)
        self.spinBox_16.setGeometry(QtCore.QRect(330, 150, 71, 31))
        self.spinBox_16.setMaximum(ln_tables_o(3))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_16.setFont(font)
        self.spinBox_16.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_16.setWrapping(True)
        self.spinBox_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_16.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_16.setSpecialValueText("")
        self.spinBox_16.setAccelerated(False)
        self.spinBox_16.setObjectName("spinBox_16")
        self.spinBox_17 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_17.setEnabled(True)
        self.spinBox_17.setGeometry(QtCore.QRect(330, 190, 71, 31))
        self.spinBox_17.setMaximum(ln_tables_o(4))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_17.setFont(font)
        self.spinBox_17.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_17.setWrapping(True)
        self.spinBox_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_17.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_17.setSpecialValueText("")
        self.spinBox_17.setAccelerated(False)
        self.spinBox_17.setObjectName("spinBox_17")
        self.spinBox_18 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_18.setEnabled(True)
        self.spinBox_18.setGeometry(QtCore.QRect(330, 230, 71, 31))
        self.spinBox_18.setMaximum(ln_tables_o(5))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_18.setFont(font)
        self.spinBox_18.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_18.setWrapping(True)
        self.spinBox_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_18.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_18.setSpecialValueText("")
        self.spinBox_18.setAccelerated(False)
        self.spinBox_18.setObjectName("spinBox_18")
        self.spinBox_19 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_19.setEnabled(True)
        self.spinBox_19.setGeometry(QtCore.QRect(330, 270, 71, 31))
        self.spinBox_19.setMaximum(ln_tables_o(6))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_19.setFont(font)
        self.spinBox_19.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_19.setWrapping(True)
        self.spinBox_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_19.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_19.setSpecialValueText("")
        self.spinBox_19.setAccelerated(False)
        self.spinBox_19.setObjectName("spinBox_19")
        self.spinBox_20 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_20.setEnabled(True)
        self.spinBox_20.setGeometry(QtCore.QRect(330, 310, 71, 31))
        self.spinBox_20.setMaximum(ln_tables_o(7))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_20.setFont(font)
        self.spinBox_20.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_20.setWrapping(True)
        self.spinBox_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_20.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_20.setSpecialValueText("")
        self.spinBox_20.setAccelerated(False)
        self.spinBox_20.setObjectName("spinBox_20")
        self.spinBox_21 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_21.setEnabled(True)
        self.spinBox_21.setGeometry(QtCore.QRect(330, 350, 71, 31))
        self.spinBox_21.setMaximum(ln_tables_o(8))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_21.setFont(font)
        self.spinBox_21.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_21.setWrapping(True)
        self.spinBox_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_21.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_21.setSpecialValueText("")
        self.spinBox_21.setAccelerated(False)
        self.spinBox_21.setObjectName("spinBox_21")
        self.spinBox_22 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_22.setEnabled(True)
        self.spinBox_22.setGeometry(QtCore.QRect(330, 390, 71, 31))
        self.spinBox_22.setMaximum(ln_tables_o(9))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_22.setFont(font)
        self.spinBox_22.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_22.setWrapping(True)
        self.spinBox_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_22.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_22.setSpecialValueText("")
        self.spinBox_22.setAccelerated(False)
        self.spinBox_22.setObjectName("spinBox_22")
        self.spinBox_23 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_23.setEnabled(True)
        self.spinBox_23.setGeometry(QtCore.QRect(330, 430, 71, 31))
        self.spinBox_23.setMaximum(ln_tables_o(10))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_23.setFont(font)
        self.spinBox_23.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_23.setWrapping(True)
        self.spinBox_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_23.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_23.setSpecialValueText("")
        self.spinBox_23.setAccelerated(False)
        self.spinBox_23.setObjectName("spinBox_23")
        self.spinBox_24 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_24.setEnabled(True)
        self.spinBox_24.setGeometry(QtCore.QRect(330, 470, 71, 31))
        self.spinBox_24.setMaximum(ln_tables_o(11))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_24.setFont(font)
        self.spinBox_24.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_24.setWrapping(True)
        self.spinBox_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_24.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_24.setSpecialValueText("")
        self.spinBox_24.setAccelerated(False)
        self.spinBox_24.setObjectName("spinBox_24")
        self.spinBox_25 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_25.setEnabled(True)
        self.spinBox_25.setGeometry(QtCore.QRect(330, 510, 71, 31))
        self.spinBox_25.setMaximum(ln_tables_o(12))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox_25.setFont(font)
        self.spinBox_25.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.spinBox_25.setWrapping(True)
        self.spinBox_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_25.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_25.setSpecialValueText("")
        self.spinBox_25.setAccelerated(False)
        self.spinBox_25.setObjectName("spinBox_25")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_16.setGeometry(QtCore.QRect(40, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        self.textBrowser_16.setFont(font)
        self.textBrowser_16.setMouseTracking(False)
        self.textBrowser_16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textBrowser_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        name_tabels = ['Кинематика', 'Динамика', 'Законы сохранения', 'Статика, гидростатика',
                       'Молекулярная физика',
                       'Термодинамика', 'Электростатика', 'Законы постоянного тока', 'Электромагнетизм',
                       'Колебания и волны', 'Оптика и СТО',
                       'Квантовая, атомная и ядерная физика']
        warning = []
        for i in range(12):
            a = len(os.listdir("Формулы ответы/"+name_tabels[i]))
            b = ln_tables(i+1)
            c = ln_tables_o(i+1)
            d = ln_tables_o_o(i+1)
            if a != b:
                warning.append(name_tabels[i] + " (формулы)")
            if c != d:
                warning.append(name_tabels[i] + " (определения)")

        pybutton = self.commandLinkButton
        if len(warning) != 0:
            pybutton.clicked.connect(self.showWarningDialog(warning))
        else:
            pybutton.clicked.connect(
            lambda: generate_work([(int(self.spinBox_12.text()), int(self.spinBox_24.text())), (int(self.spinBox_4.text()),
                              int(self.spinBox_16.text())), (int(self.spinBox_10.text()), int(self.spinBox_22.text())), (int(self.spinBox_8.text()), int(self.spinBox_20.text())),
                           (int(self.spinBox_3.text()), int(self.spinBox_15.text())), (int(self.spinBox_5.text()), int(self.spinBox_17.text())), (int(self.spinBox_9.text()),
                              int(self.spinBox_21.text())), (int(self.spinBox_13.text()), int(self.spinBox_25.text())), (int(self.spinBox_6.text()), int(self.spinBox_18.text())), (int(self.spinBox_4.text()),
                              int(self.spinBox_16.text())), (int(self.spinBox_11.text()), int(self.spinBox_23.text())), (int(self.spinBox.text()), int(self.spinBox_2.text()))], int(self.spinBox_14.text())))
            pybutton.clicked.connect(self.showDialog)

    def showWarningDialog(self, warning):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Warning)
        msgBox.setText("Количество вопросов и ответов не соотвествует в темах: " + str(warning).replace("'", "")[1:-1])
        msgBox.setWindowTitle("Осторожно")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()
    def showDialog(self):
        msgBox = QMessageBox()
        msgBox.setIcon(QMessageBox.Information)
        msgBox.setText("Варианты успешно созданы!")
        msgBox.setWindowTitle("Поздравляю")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создание физдиктанта"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">По </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">формулам</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MV Boli\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sylfaen\'; font-size:11pt;\">По </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sylfaen\'; font-size:11pt;\">определениям</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Кинематика</p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Динамика</p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Законы сохранения</p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Статика, гидростатика</p></body></html>"))
        self.textBrowser_7.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Молекулярная физика</p></body></html>"))
        self.textBrowser_8.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Термодинамика</p></body></html>"))
        self.textBrowser_9.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Электростатика</p></body></html>"))
        self.textBrowser_10.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Законы постоянного тока</p></body></html>"))
        self.textBrowser_11.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Электромагнетизм</p></body></html>"))
        self.textBrowser_12.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Колебания и волны</p></body></html>"))
        self.textBrowser_13.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Оптика и СТО</p></body></html>"))
        self.textBrowser_14.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Квантовая и атомная физика</p></body></html>"))
        self.textBrowser_15.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Количество вариантов</span></p></body></html>"))
        self.commandLinkButton.setText(_translate("Dialog", "Создать варианты"))
        self.textBrowser_16.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sylfaen\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Темы</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Варианты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Добавление вопросов"))